### ISSUE TITLE
php notice

### ISSUE THREAD

**Issue by Protohominid** [rayman813/smashing-plugin#1]
Hey, I'm get a php notice:
Notice: Undefined property: stdClass::$checked in /.../updater.php on line 79

It's just a notice so no big deal, just thought I'd throw it out there. I'm still unable to get this to work with my plugin, but I'm assuming it's unrelated to this undefined property notice.

Also wondering why the if conditional on that line uses "=" and not "==". Is that a typo?

**Comment by rayman813** [comment]
This undefined property should be fixed in the latest code. Do you want to open a new issue for the thing you were seeing inconsistent update notifications?

Thanks!

**Comment by Protohominid** [comment]
Thanks! I'll let you know how it goes.
