### ISSUE TITLE
undefined index in version_compare

### ISSUE THREAD

**Issue by eberhapa** [rayman813/smashing-plugin#10]
Hi,

Why do I get undefined index in version_compare. While debugging it seems that `$this->basename` is empty. But its not always.

Best,
Patrick

**Comment by scottshefler** [comment]
Getting same error. Would love an update and also an update for GitHub's personal token API changes.

**Comment by rayman813** [comment]
I have merged in the pull request here: https://github.com/rayman813/smashing-updater-plugin/pull/12
