### ISSUE TITLE
Update Failed: Download failed. A valid URL was not provided.

### ISSUE THREAD

**Issue by hounw** [rayman813/smashing-plugin#11]
I'm trying to use this code with access token but when I try to update the plugin I get this error...

Update Failed: Download failed. A valid URL was not provided.

I error_logged the download url and it works but instead of downloading the normal repo-version.zip it download a super long file name that includes all the url parameters, and worst part is that when you unzip it the folder inside is not the original plugin folder  name but that same long path:

https://api.github.com/repos/hounw/webifica_pagalo_wc/zipball/0.0.4?access_token=39196691ba623b51466ea71e8e380b22a9bcd4ab

**Comment by MilesS** [comment]
Try my fork: https://github.com/MilesS/smashing-updater-plugin

I have a pull request to fix the auth-token issue

**Comment by hounw** [comment]
Will do thanks!

**Comment by rayman813** [comment]
Thank you @MilesS! Merged your change into master!

**Comment by MilesS** [comment]
Awesome!
