### ISSUE TITLE
Token Change

### ISSUE THREAD

**Issue by ChristinaSW** [rayman813/smashing-plugin#14]
On line 56 in the updater.php file it says token, but it should say Bearer.

I started working with this and came across it.

I was able to get the repository information, but it got lost again somewhere along the way, so I had to just change my repo to public.

Otherwise, this code is awesome. Thanks for sharing it!

**Comment by rayman813** [comment]
Thanks for the input! Added here: 4a8259eeb982f370c309b273c988bd30538ba301
