### ISSUE TITLE
Plugin Details aren't showing when updating

### ISSUE THREAD

**Issue by celsom3** [rayman813/smashing-plugin#2]
When a new update is detected, and the plugin info should be pulled and displayed [via plugin_popup()], an error shows up instead:

An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums.

The light works, but instead of displaying info, just the error message appears (see below). I tried to figure out the problem. Maybe I'm just a noob, but I couldn't see a referenced to the 'plugins_api'  hook in the filter added in the initialize() function.

![Screenshot](http://s27.postimg.org/48ctvchf7/Screen_Shot_2016_01_12_at_12_12_38_PM.png)

**Comment by rayman813** [comment]
Resolved in commit: f4a19234dcd3fadca66eee5d3e8440834f5cf59c
