### ISSUE TITLE
Update now infinite loading

### ISSUE THREAD

**Issue by reesher** [rayman813/smashing-plugin#4]
Hi,
I'm not sure if this issue is only on my side, but when i click on "Update now" button trough Plugins page, my plugin actually updates but the "process" (moving arrow - updating) is stuck in infinite loop and notification about state of updating won't show up.

https://gyazo.com/1449221a2fb7fa1135e0c2b159037c7b

**Comment by celsom3** [comment]
Yes, that happens on my end as well. I just refresh the page after a bit
and it is updated, but haven't looked into why it does that.

**Comment by rayman813** [comment]
Testing this on fresh install of repo and not getting the issue. From the sound of it, though, it may be pulling down the zip file from git and your server connection is slow for some reason (causing a delay in the update). This is just speculation, so I can't say for sure. Would either of you be able to send me a copy of your plugin so I can rule out any conflicts/stack errors?

**Comment by reesher** [comment]
Yup, here it is. https://github.com/reesher/XAR

Thanks in advance.

**Comment by rayman813** [comment]
I think I may have tracked down the issue. The AJAX response from the plugin updater is not getting a new version:

![image](https://cloud.githubusercontent.com/assets/2110153/12597599/c8a14844-c453-11e5-918b-0c3a268b0e19.png)

I took a look through the core and I think what is happening is the version number in your release and your version number in your comments are mismatched. It seems like you may have already noticed this based on your commit here: 

https://github.com/reesher/XAR/commit/c4f431fac48f00f46e4a6a5c8e0605a8349c4999

Try adding a new release and make sure the tag and the version in the comments match and see if that fixes your issue.

**Comment by reesher** [comment]
I fixed the ver info/release to match, but I still experience the problem.

**Comment by jordachewd** [comment]
I have the same issue here.
When hit "Update Now" from plugins page I get an infinite loop .
When hit "Install Now" button in the View Details popup I get this error message 
![updater](https://cloud.githubusercontent.com/assets/5006059/14040807/8419bbae-f273-11e5-9423-6ce83059cb57.jpg)

I suspect there is a nonce that doesn't verify correctly during the update process but I have no idea (yet) how to fix it.

Any hint will be much appreciated.
Thank you

**Comment by hrsetyono** [comment]
Hi, I got the same problem on both WordPress 4.4 and 4.5

```
Uncaught Error: Syntax error, unrecognized expression: #myplugin/index.php
```

I have made sure the Release and Comment version is the same.

Anyone solved this? Thanks

**Comment by mrozbarry** [comment]
On Wordpress 4.7.3, I don't get this error on my local development server. I have no other plugins installed, and a public github repository. Just wanted to comment to say either the issue is resolved and should be closed, or it's likely a per-plugin bug rather than the `Smashing_Updater` implementation itself.

**Comment by rayman813** [comment]
@mrozbarry Thanks for the confirmation, I'll mark as closed.
