### ISSUE TITLE
Secure Personal Access Token

### ISSUE THREAD

**Issue by megphillips91** [rayman813/smashing-plugin#7]
Wondering if you've used this in production with a premium plugin which lives in a private repository? 

I am concerned about the personal access token living right there inside plugin.php. Have you a suggestion or link you could share which addresses this and maybe proposes a workflow to protect and/or conceal the access token?

Thank you,
Meg

**Comment by jmorfis** [comment]
wondering same exact thing

**Comment by rayman813** [comment]
I have not actually ever used the access token feature myself. I also realize that there is an inherent risk in having it in the codebase as plain text so I would definitely not recommend that unless you want people to have unfettered access to the plugin. If you MUST have a private plugin then my suggestion would actually be to use a callback to reach out to a tokens environment and set the access token in the database for the plugin to use. You still are not safe from very persistent individuals but you wouldn't have sensitive info in your repos, either. There are probably better ways to protect these values as well, using encryption like mcrypt or similar, but to keep the plugin very accessible I left the code as simple as I could. Hope this helps!
