### ISSUE TITLE
Auth-tokens no longer allowed in query.

### ISSUE THREAD

**Issue by Pejyuu** [rayman813/smashing-plugin#8]
I got this e-mail from Github after I made this into a part of my plugin. 
It works great, but considering some of the functionality is deprecated on github and probably won't be supported for much longer, it's something to look into or notify people of if you don't intend to update this snippet of code.

___ 
Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
____

I'll figure this out on my own if you don't update it, but I figured I should notify of this either way.

**Comment by ahmadthedev** [comment]
Hi @Pejyuu, I'm getting the same error, can you help me to fix it?

**Comment by addzycullen** [comment]
Do you still need help with this? I've done it today so happy to help

In your updater.php, replace the following function: 

```
private function get_repository_info() {
    if ( is_null( $this->github_response ) ) { // Do we have a response?
        $request_uri = sprintf( 'https://api.github.com/repos/%s/%s/releases', $this->username, $this->repository ); // Build URI

        if( $this->authorize_token ) { // Is there an access token?
            $request_uri = add_query_arg( 'access_token', $this->authorize_token, $request_uri ); // Append it
        }

        $response = json_decode( wp_remote_retrieve_body( wp_remote_get( $request_uri ) ), true ); // Get JSON and parse it

        if( is_array( $response ) ) { // If it is an array
            $response = current( $response ); // Get the first item
        }

       if( $this->authorize_token ) { // Is there an access token?
	   $response['zipball_url'] = add_query_arg( 'access_token', $this->authorize_token, 
           $response['zipball_url'] ); // Update our zip url with token
        }

        $this->github_response = $response; // Set it to our property
    }
}
```

with this 

```
private function get_repository_info() {
    if ( is_null( $this->github_response ) ) { // Do we have a response?
        $args = array();
        $request_uri = sprintf( 'https://api.github.com/repos/%s/%s/releases', $this->username, $this->repository ); // Build URI

        if ( $this->authorize_token ) { // Is there an access token?
            $args = array(
	        "headers" => array(
	            "Authorization" => "token {$this->authorize_token}"
	         )
	    );
        }

        $response = json_decode( wp_remote_retrieve_body( wp_remote_get( $request_uri, $args ) ), true ); // Get JSON and parse it

        if( is_array( $response ) ) { // If it is an array
            $response = current( $response ); // Get the first item
        }

        if( $this->authorize_token ) { // Is there an access token?
            $response['zipball_url'] = add_query_arg( 'access_token', $this->authorize_token, 
            $response['zipball_url'] ); // Update our zip url with token
        }

        $this->github_response = $response; // Set it to our property
    }
}
```

@rayman813 I've submitted a pull request that fixes this deprecation notice :)

**Comment by Pejyuu** [comment]
Nice, thank you @addzycullen !

**Comment by Pejyuu** [comment]
I've tried this now, and for some reason I seem to be getting some memory-allocation problems. 
It goes away if I remove the updater code from the plugin file. 

Anything you've experienced, @addzycullen  ?

**Comment by addzycullen** [comment]
@Pejyuu No it's been working perfectly for me since.  

Have you got WP_Debug turned on? Whats the complete error saying?

**Comment by Pejyuu** [comment]
> 
> 
> @Pejyuu No it's been working perfectly for me since.
> 
> Have you got WP_Debug turned on? Whats the complete error saying?

`
Fatal error: Allowed memory size of 1048576000 bytes exhausted (tried to allocate 20480 bytes) in <removed>\wp-includes\functions.php on line 4306

Fatal error: Allowed memory size of 1048576000 bytes exhausted (tried to allocate 20480 bytes) in <removed>\wp-includes\functions.php on line 6066
`

It errors out on different things though, I need to comment out the entire updater for it to work. Not just change this back to how it was.

**Comment by Pejyuu** [comment]
Oh, I think I did it. I'd been dabbling with trying to fix this on my own earlier. Forgot to remove that code, so it was probably making a mess of it all. 

Nevermind me :D 
Solution supplies by @addzycullen works fine!

**Comment by addzycullen** [comment]
@Pejyuu No worries, glad you fixed it :)

**Comment by hounw** [comment]
@addzycullen but like the token will still be used to get the download zipball  no?

Also I can't get it to work now... as stated in the issue #11 

Any help guidance will be greatly appreciated.
